map $request_uri $wrapper_acs {
    default "{{SERVER_ROOT}}/wrapper/core/auth_checker.php";
    
    ~^/ianseo/(Api/ISK-NG/|TV/Rot/|TV/Photos/) "";
    ~^/(auth\.php|login\.php|index\.php) "";
}

server {
        listen 80;
        listen [::]:80;

        server_name {{SERVER_NAME}};

        root {{SERVER_ROOT}};

	client_max_body_size 256M;

        index index.php;

        access_log /var/log/nginx/{{SERVER_NAME}}_access.log combined_realip;
        error_log /var/log/nginx/{{SERVER_NAME}}_error.log;

    location / {
        if (!-e $request_filename) {
            rewrite ^/(.*)$ /ianseo/$1 last;
        }
    }

    location ~ \.php$ {
        if (!-e $request_filename) {
            rewrite ^/(.*)$ /ianseo/$1 last;
        }

        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;

        fastcgi_param PHP_VALUE "auto_prepend_file=$wrapper_acs";
    }

}
